### ISSUE TITLE
Vagrant update

### ISSUE THREAD

**Issue by Raphael-Lemaire** [lmeryFulbert/vagrant-ansible-mariadb#1]
J'ai remarqué une erreur lors de l'exécution de la commande "vagrant provision" le fichier playbook.yml est introuvable car la route n'est pas correct et donc à modifier dans le fichier vagrantfile :

Ligne 74 : ansible.playbook = "./anisble/playbook.yml"

Réécrire le dans la route le mot "anisble" en "ansible".

**Comment by lmeryFulbert** [comment]
bug fixed, anisble folder delete and ansible folder create.
Thanks

**Comment by lmeryFulbert** [comment]
issue closed
